using System.Collections.Generic;
namespace MhwOverlay.Config
{
    public class MonsterDataConfig
    {
        public Dictionary<string, string> Monsters = new Dictionary<string, string>()
        {
            {"em001_00", "LOC_MONSTER_RATHIAN"},
            {"em001_01", "LOC_MONSTER_PINK_RATHIAN"},
            {"em001_02", "LOC_MONSTER_GOLD_RATHIAN"},
            {"em002_00", "LOC_MONSTER_RATHALOS"},
            {"em002_01", "LOC_MONSTER_AZURE_RATHALOS"},
            {"em002_02", "LOC_MONSTER_SILVER_RATHALOS"},
            {"em007_00", "LOC_MONSTER_DIABLOS"},
            {"em007_01", "LOC_MONSTER_BLACK_DIABLOS"},
            {"em011_00", "LOC_MONSTER_KIRIN"},
            {"em018_00", "LOC_MONSTER_YIAN_GARUGA"},
            {"em018_05", "LOC_MONSTER_SCARRED_YIAN_GARUGA"},
            {"em024_00", "LOC_MONSTER_KUSHALA_DAORA"},
            {"em026_00", "LOC_MONSTER_LUNASTRA"},
            {"em027_00", "LOC_MONSTER_TEOSTRA"},
            {"em032_00", "LOC_MONSTER_TIGREX"},
            {"em032_01", "LOC_MONSTER_BRUTE_TIGREX"},
            {"em036_00", "LOC_MONSTER_LAVASIOTH"},
            {"em037_00", "LOC_MONSTER_NARGACUGA"},
            {"em042_00", "LOC_MONSTER_BARIOTH"},
            {"em043_00", "LOC_MONSTER_DEVILJHO"},
            {"em043_05", "LOC_MONSTER_SAVAGE_DEVILJHO"},
            {"em044_00", "LOC_MONSTER_BARROTH"},
            {"em045_00", "LOC_MONSTER_URAGAAN"},
            {"em057_00", "LOC_MONSTER_ZINOGRE"},
            {"em063_00", "LOC_MONSTER_BRACHYDIOS"},
            {"em080_00", "LOC_MONSTER_GLAVENUS"},
            {"em080_01", "LOC_MONSTER_ACIDIC_GLAVENUS"},
            {"em100_00", "LOC_MONSTER_ANJANATH"},
            {"em100_01", "LOC_MONSTER_ANJANATH_FULGUR"},
            {"em101_00", "LOC_MONSTER_GREAT_JAGRAS"},
            {"em102_00", "LOC_MONSTER_PUKEI_PUKEI"},
            {"em102_01", "LOC_MONSTER_PUKEI_PUKEI_CORAL"},
            {"em103_00", "LOC_MONSTER_NERGIGANTE"},
            {"em103_05", "LOC_MONSTER_RUINER_NERGIGANTE"},
            {"em105_00", "LOC_MONSTER_XENO_JIIVA"},
            {"em106_00", "LOC_MONSTER_ZORAH_MAGDAROS"},
            {"em107_00", "LOC_MONSTER_KULU_YA_KU"},
            {"em108_00", "LOC_MONSTER_JYURATODUS"},
            {"em109_00", "LOC_MONSTER_TOBI_KADACHI"},
            {"em109_01", "LOC_MONSTER_VIPER_TOBI_KADACHI"},
            {"em110_00", "LOC_MONSTER_PAOLUMU"},
            {"em110_01", "LOC_MONSTER_PAOLUMU_NIGHTSHADE"},
            {"em111_00", "LOC_MONSTER_LEGIANA"},
            {"em111_05", "LOC_MONSTER_SHRIEKING_LEGIANA"},
            {"em112_00", "LOC_MONSTER_GREAT_GIRROS"},
            {"em113_00", "LOC_MONSTER_ODOGARON"},
            {"em113_01", "LOC_MONSTER_EBONY_ODOGARON"},
            {"em114_00", "LOC_MONSTER_RADOBAAN"},
            {"em115_00", "LOC_MONSTER_VAAL_HAZAK"},
            {"em115_05", "LOC_MONSTER_BLACKVEIL_VAAL_HAZAK"},
            {"em116_00", "LOC_MONSTER_DODOGAMA"},
            {"em117_00", "LOC_MONSTER_KULVE_TAROTH"},
            {"em118_00", "LOC_MONSTER_BAZELGEUSE"},
            {"em118_05", "LOC_MONSTER_SEETHING_BAZELGEUSE"},
            {"em120_00", "LOC_MONSTER_TZITZI_YA_KU"},
            {"em121_00", "LOC_MONSTER_BEHEMOTH"},
            {"em122_00", "LOC_MONSTER_BEOTODUS"},
            {"em123_00", "LOC_MONSTER_BANBARO"},
            {"em124_00", "LOC_MONSTER_VELKHANA"},
            {"em125_00", "LOC_MONSTER_NAMIELLE"},
            {"em126_00", "LOC_MONSTER_SHARA_ISHVALDA"},
            {"em127_00", "LOC_MONSTER_LESHEN"}
        };
    }
}
